# Generated by Django 2.1.5 on 2019-01-14 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netdash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='network_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='netdash.NetworkBoard'),
        ),
        migrations.AddField(
            model_name='networkboard',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_board', to='netdash.Unit'),
        ),
        migrations.AddField(
            model_name='message',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='netdash.Unit'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='netdash.Unit'),
        ),
    ]
